### ISSUE TITLE
失败 invalid request

### ISSUE THREAD

**Issue by wizardt** [daye99/genshin-sign-helper#5]
使用EDGE浏览器，我能看到cookies的内容和reademe里写的，不同字段的顺序不同。 比如UM_distinctid并不是在首位，而是出现在了后面。 第一个的反而是 mihoyoID。也许是因为这个原因？需要自行调整一下顺序？

**Comment by wizardt** [comment]
啊，更新一下情况。也许是因为该账号当天已经签过到导致的失败。但确实COOKIES中的字段顺序不一致，不知道是否有影响？

>

**Comment by daye99** [comment]
...close了
